// <auto-generated />
using System;
using DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataLayer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221129125749_add_data")]
    partial class adddata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("DataLayer.Models.Game", b =>
                {
                    b.Property<int>("game_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("game_enddate")
                        .HasColumnType("TEXT");

                    b.Property<int>("game_num1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("game_num2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("game_num3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("game_num4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("game_num5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("game_num6")
                        .HasColumnType("INTEGER");

                    b.Property<int>("game_prize")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("game_startdate")
                        .HasColumnType("TEXT");

                    b.HasKey("game_id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("DataLayer.Models.Player", b =>
                {
                    b.Property<int>("player_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Playersplayer_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("game_id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("game_id1")
                        .HasColumnType("INTEGER");

                    b.Property<string>("player_code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("player_num1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("player_num2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("player_num3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("player_num4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("player_num5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("player_num6")
                        .HasColumnType("INTEGER");

                    b.Property<int>("player_prize")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("player_reg_date")
                        .HasColumnType("TEXT");

                    b.HasKey("player_id");

                    b.HasIndex("Playersplayer_id");

                    b.HasIndex("game_id1");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("DataLayer.Models.Player", b =>
                {
                    b.HasOne("DataLayer.Models.Player", "Players")
                        .WithMany()
                        .HasForeignKey("Playersplayer_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataLayer.Models.Game", null)
                        .WithMany("Players")
                        .HasForeignKey("game_id1");

                    b.Navigation("Players");
                });

            modelBuilder.Entity("DataLayer.Models.Game", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
